version: 2
jobs:
  build:
    branches:
      only:
        - PS-004
    docker:
          - image: circleci/openjdk:11.0
    working_directory: ~/circleci-demo-java-spring
    steps:
      - checkout
      - run: mvn clean package assembly:assembly
      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/data_fetcher_0.0.1.jar