version: 2
jobs:
  build:
    branches:
      only:
        - PS-004
    docker:
          - image: circleci/openjdk:11.0
    working_directory: ~/data_fetcher
    steps:
      - checkout
      - run: mvn clean package assembly:assembly
      - run:
          command: mkdir ~/data_fetcher/artifacts;
      - run:
          command: mkdir ~/data_fetcher/surefire-reports;
      - store_test_results:
          path: ~/data_fetcher/surefire-reports

      - store_artifacts:
          path: ~/data_fetcher/artifacts/data_fetcher_0.0.1.jar