version: 2
jobs:
  build:
    branches:
      only:
        - PS-004
    docker:
          - image: circleci/openjdk:11.0
    working_directory: ~/data_fetcher
    steps:
      - checkout
      - run: mvn clean package assembly:assembly
      - store_artifacts:
          path: ~/data_fetcher/target/data_fetcher-1.0-SNAPSHOT-jar-with-dependencies.jar
