/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pagisoft.datafetcher.model.allegro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Publication extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5092180267305612313L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Publication\",\"namespace\":\"com.pagisoft.datafetcher.model.allegro\",\"fields\":[{\"name\":\"endingAt\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Publication> ENCODER =
      new BinaryMessageEncoder<Publication>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Publication> DECODER =
      new BinaryMessageDecoder<Publication>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Publication> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Publication> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Publication>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Publication to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Publication from a ByteBuffer. */
  public static Publication fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String endingAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Publication() {}

  /**
   * All-args constructor.
   * @param endingAt The new value for endingAt
   */
  public Publication(java.lang.String endingAt) {
    this.endingAt = endingAt;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return endingAt;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: endingAt = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'endingAt' field.
   * @return The value of the 'endingAt' field.
   */
  public java.lang.String getEndingAt() {
    return endingAt;
  }

  /**
   * Sets the value of the 'endingAt' field.
   * @param value the value to set.
   */
  public void setEndingAt(java.lang.String value) {
    this.endingAt = value;
  }

  /**
   * Creates a new Publication RecordBuilder.
   * @return A new Publication RecordBuilder
   */
  public static com.pagisoft.datafetcher.model.allegro.Publication.Builder newBuilder() {
    return new com.pagisoft.datafetcher.model.allegro.Publication.Builder();
  }

  /**
   * Creates a new Publication RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Publication RecordBuilder
   */
  public static com.pagisoft.datafetcher.model.allegro.Publication.Builder newBuilder(com.pagisoft.datafetcher.model.allegro.Publication.Builder other) {
    return new com.pagisoft.datafetcher.model.allegro.Publication.Builder(other);
  }

  /**
   * Creates a new Publication RecordBuilder by copying an existing Publication instance.
   * @param other The existing instance to copy.
   * @return A new Publication RecordBuilder
   */
  public static com.pagisoft.datafetcher.model.allegro.Publication.Builder newBuilder(com.pagisoft.datafetcher.model.allegro.Publication other) {
    return new com.pagisoft.datafetcher.model.allegro.Publication.Builder(other);
  }

  /**
   * RecordBuilder for Publication instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Publication>
    implements org.apache.avro.data.RecordBuilder<Publication> {

    private java.lang.String endingAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.pagisoft.datafetcher.model.allegro.Publication.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.endingAt)) {
        this.endingAt = data().deepCopy(fields()[0].schema(), other.endingAt);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Publication instance
     * @param other The existing instance to copy.
     */
    private Builder(com.pagisoft.datafetcher.model.allegro.Publication other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.endingAt)) {
        this.endingAt = data().deepCopy(fields()[0].schema(), other.endingAt);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'endingAt' field.
      * @return The value.
      */
    public java.lang.String getEndingAt() {
      return endingAt;
    }

    /**
      * Sets the value of the 'endingAt' field.
      * @param value The value of 'endingAt'.
      * @return This builder.
      */
    public com.pagisoft.datafetcher.model.allegro.Publication.Builder setEndingAt(java.lang.String value) {
      validate(fields()[0], value);
      this.endingAt = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'endingAt' field has been set.
      * @return True if the 'endingAt' field has been set, false otherwise.
      */
    public boolean hasEndingAt() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'endingAt' field.
      * @return This builder.
      */
    public com.pagisoft.datafetcher.model.allegro.Publication.Builder clearEndingAt() {
      endingAt = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Publication build() {
      try {
        Publication record = new Publication();
        record.endingAt = fieldSetFlags()[0] ? this.endingAt : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Publication>
    WRITER$ = (org.apache.avro.io.DatumWriter<Publication>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Publication>
    READER$ = (org.apache.avro.io.DatumReader<Publication>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
