/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pagisoft.datafetcher.model.allegro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Seller extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4392782956360421123L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Seller\",\"namespace\":\"com.pagisoft.datafetcher.model.allegro\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"company\",\"type\":\"boolean\"},{\"name\":\"superSeller\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Seller> ENCODER =
      new BinaryMessageEncoder<Seller>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Seller> DECODER =
      new BinaryMessageDecoder<Seller>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Seller> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Seller> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Seller>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Seller to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Seller from a ByteBuffer. */
  public static Seller fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String id;
  @Deprecated public boolean company;
  @Deprecated public boolean superSeller;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Seller() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param company The new value for company
   * @param superSeller The new value for superSeller
   */
  public Seller(java.lang.String id, java.lang.Boolean company, java.lang.Boolean superSeller) {
    this.id = id;
    this.company = company;
    this.superSeller = superSeller;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return company;
    case 2: return superSeller;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    case 1: company = (java.lang.Boolean)value$; break;
    case 2: superSeller = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'company' field.
   * @return The value of the 'company' field.
   */
  public java.lang.Boolean getCompany() {
    return company;
  }

  /**
   * Sets the value of the 'company' field.
   * @param value the value to set.
   */
  public void setCompany(java.lang.Boolean value) {
    this.company = value;
  }

  /**
   * Gets the value of the 'superSeller' field.
   * @return The value of the 'superSeller' field.
   */
  public java.lang.Boolean getSuperSeller() {
    return superSeller;
  }

  /**
   * Sets the value of the 'superSeller' field.
   * @param value the value to set.
   */
  public void setSuperSeller(java.lang.Boolean value) {
    this.superSeller = value;
  }

  /**
   * Creates a new Seller RecordBuilder.
   * @return A new Seller RecordBuilder
   */
  public static com.pagisoft.datafetcher.model.allegro.Seller.Builder newBuilder() {
    return new com.pagisoft.datafetcher.model.allegro.Seller.Builder();
  }

  /**
   * Creates a new Seller RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Seller RecordBuilder
   */
  public static com.pagisoft.datafetcher.model.allegro.Seller.Builder newBuilder(com.pagisoft.datafetcher.model.allegro.Seller.Builder other) {
    return new com.pagisoft.datafetcher.model.allegro.Seller.Builder(other);
  }

  /**
   * Creates a new Seller RecordBuilder by copying an existing Seller instance.
   * @param other The existing instance to copy.
   * @return A new Seller RecordBuilder
   */
  public static com.pagisoft.datafetcher.model.allegro.Seller.Builder newBuilder(com.pagisoft.datafetcher.model.allegro.Seller other) {
    return new com.pagisoft.datafetcher.model.allegro.Seller.Builder(other);
  }

  /**
   * RecordBuilder for Seller instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Seller>
    implements org.apache.avro.data.RecordBuilder<Seller> {

    private java.lang.String id;
    private boolean company;
    private boolean superSeller;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.pagisoft.datafetcher.model.allegro.Seller.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.company)) {
        this.company = data().deepCopy(fields()[1].schema(), other.company);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.superSeller)) {
        this.superSeller = data().deepCopy(fields()[2].schema(), other.superSeller);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Seller instance
     * @param other The existing instance to copy.
     */
    private Builder(com.pagisoft.datafetcher.model.allegro.Seller other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.company)) {
        this.company = data().deepCopy(fields()[1].schema(), other.company);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.superSeller)) {
        this.superSeller = data().deepCopy(fields()[2].schema(), other.superSeller);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.pagisoft.datafetcher.model.allegro.Seller.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.pagisoft.datafetcher.model.allegro.Seller.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'company' field.
      * @return The value.
      */
    public java.lang.Boolean getCompany() {
      return company;
    }

    /**
      * Sets the value of the 'company' field.
      * @param value The value of 'company'.
      * @return This builder.
      */
    public com.pagisoft.datafetcher.model.allegro.Seller.Builder setCompany(boolean value) {
      validate(fields()[1], value);
      this.company = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'company' field has been set.
      * @return True if the 'company' field has been set, false otherwise.
      */
    public boolean hasCompany() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'company' field.
      * @return This builder.
      */
    public com.pagisoft.datafetcher.model.allegro.Seller.Builder clearCompany() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'superSeller' field.
      * @return The value.
      */
    public java.lang.Boolean getSuperSeller() {
      return superSeller;
    }

    /**
      * Sets the value of the 'superSeller' field.
      * @param value The value of 'superSeller'.
      * @return This builder.
      */
    public com.pagisoft.datafetcher.model.allegro.Seller.Builder setSuperSeller(boolean value) {
      validate(fields()[2], value);
      this.superSeller = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'superSeller' field has been set.
      * @return True if the 'superSeller' field has been set, false otherwise.
      */
    public boolean hasSuperSeller() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'superSeller' field.
      * @return This builder.
      */
    public com.pagisoft.datafetcher.model.allegro.Seller.Builder clearSuperSeller() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Seller build() {
      try {
        Seller record = new Seller();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.company = fieldSetFlags()[1] ? this.company : (java.lang.Boolean) defaultValue(fields()[1]);
        record.superSeller = fieldSetFlags()[2] ? this.superSeller : (java.lang.Boolean) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Seller>
    WRITER$ = (org.apache.avro.io.DatumWriter<Seller>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Seller>
    READER$ = (org.apache.avro.io.DatumReader<Seller>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
